# Generated by Django 5.0 on 2023-12-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="user_id",
            field=models.UUIDField(),
        ),
    ]
