# Generated by Django 5.0 on 2023-12-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes_user_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
